### PR TITLE
Click accept pull request for free iphone 5s

### PR DESCRIPTION
**Pull request by Cyclic3**

### CODE REVIEW

**Comment by Cyclic3** [comment]
please I want to give free androind phon

**Comment by Cyclic3** [comment]
no man pls

**Comment by Cyclic3** [comment]
pls

**Comment by ElliottDG** [comment]
no u

**Comment by Cyclic3** [comment]
repope now

**Comment by ElliottDG** [comment]
repope 😊

**Comment by Douile** [comment]
Why is this not merged @ElliottDG

**Comment by ElliottDG** [comment]
bc no u

**Pull request closed without merging**
